language: java
jdk:
    - openjdk8
    - openjdk11
branches:
  only:
    - master
    - dev
    - 3.x
services:
  - redis-server
before_install:
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk8 --target $JAVA_HOME
  - ls $HOME/openjdk11
  - cp ./toolchains.xml ~/.m2/
  - wget https://github.com/antirez/redis/archive/3.2.3.tar.gz
  - tar -xvzf 3.2.3.tar.gz >/dev/null 2>&1
  - cd redis-3.2.3
  - make >/dev/null 2>&1
  - cd src && nohup ./redis-server --port 6380 --requirepass test &
  - cd ..
before_script:
  - sleep 10
script: "mvn clean package -P travis --batch-mode --quiet"
after_success:
  - mvn clean test jacoco:report coveralls:report --batch-mode --quiet